= Sharing and Reusing Custom DataWeave Modules and Mappings
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

DataWeave enables you to implement, test, and package your custom DataWeave modules and mappings into libraries that you can share and reuse through Anypoint Exchange.

The xref:dataweave-extension-plugin.adoc[DataWeave 2.0 extension to Visual Studio Code] enhances productivity when you are building DataWeave libraries. The extension provides the following capabilities:

* Ability to work on your DataWeave modules and mappings in a standalone manner, outside of a Mule application.
* Instant execution of your DataWeave mappings, including live preview of data transformations.
* Language support, including autocompletion, navigation, refactoring, formatting, quick fixes, and syntax highlighting.
* Debugging support for DataWeave mappings.
* Automatic generation of a documentation template that you can use to provide your own xref:dataweave-create-module.adoc#docs-dw-lib[DataWeave library documentation] in Exchange.
* An embedded xref:dataweave-maven-plugin.adoc[DataWeave Maven plugin] with the following features:
** Integration of packaging and deployment of your DataWeave libraries with your Maven lifecycle.
** Integration with Exchange to share and consume DataWeave libraries.
* An embedded xref:dataweave-testing-framework.adoc[DataWeave testing framework] that enables you to build automated unit and integration tests easily.
