= DataWeave System Properties
:page-aliases: 4.3@mule-runtime::dataweave-system-properties.adoc

DataWeave supports several system properties. To use these properties in application development and deployments, see xref:4.3@mule-runtime::mule-app-properties-system.adoc[System Properties].

[%header%autowidth.spread,cols=",a"]
|===
|Property |Description

//com.mulesoft.dw.buffer.memory.monitoring//
|`com.mulesoft.dw.buffer.memory.monitoring`|
_Experimental:_ When set to `true`, logs a message each time a slot from the memory pool is taken or released. The behavior is useful for troubleshooting.
`com.mulesoft.dw.buffer.memory.monitoring` supports an _experimental feature_ that is subject to change or removal from future versions of DataWeave.

* Type: `Boolean`
* Default: `false`


//com.mulesoft.dw.buffersize//
|`com.mulesoft.dw.buffersize`|
Sets the size (in bytes) of in-memory input and output buffers that DataWeave uses to retain processed inputs and outputs.
DataWeave stores payloads that exceed this size in temporary files `dw-buffer-index-${count}.tmp` and `dw-buffer-output-${count}.tmp`.
See xref:dataweave-memory-management.adoc[DataWeave Memory Management].

* Type: `Number` (in bytes)
* Default: `8192` bytes (8 KB)


//com.mulesoft.dw.coercionexception.verbose//
|`com.mulesoft.dw.coercionexception.verbose`|
By default, adds to coercion exceptions more information about data that fails to coerce. When this property is set to `false`, DataWeave does not display the additional metadata.

* Type: `Boolean`
* Default: `true`


//com.mulesoft.dw.date_minus_back_compatibility//
|`com.mulesoft.dw.date_minus_back_compatibility`|
Restores the xref:dataweave-cookbook-add-and-subtract-time.adoc[Add and Subtract Time] behaviors that changed in 2.3.0 when this property is set to `true`.

* Type: `Boolean`
* Default: `false`

For example, consider the following DataWeave script:
[source,dataweave,linenums]
----
%dw 2.0
output application/dw
---
\|2019-10-01\| - \|2018-09-23\|
----
* In DataWeave 2.3.0, the expression returns `PT8952H`.
* In DataWeave 2.2.0, the expression returns `P1Y8D`.


//com.mulesoft.dw.directbuffer.disable//
|`com.mulesoft.dw.directbuffer.disable`|
Controls whether DataWeave uses off-heap memory (the default) or heap memory. DataWeave uses off-heap memory for internal buffering, which can cause issues on systems that have only a small amount of memory. See xref:dataweave-memory-management.adoc[DataWeave Memory Management].

* Type: `Boolean`
* Default: `false`


//com.mulesoft.dw.dump_files//
|`com.mulesoft.dw.dump_files`|
_Experimental:_ Dumps the input context and the failing script into a folder when this property is set to `true`. This behavior enables you to track the failing script and the data that makes the script fail, which is particularly useful for verifying that the received input data is valid. Incorrect scripts often fail when an upstream component generates invalid data.

* Type: `Boolean`
* Default: `false`

`com.mulesoft.dw.dump_files` is an _experimental feature_ that is subject to change or removal from future versions of DataWeave. See xref:dataweave-troubleshoot.adoc[Troubleshooting a Failing DataWeave Script].


//com.mulesoft.dw.dump_folder//
|`com.mulesoft.dw.dump_folder`|
_Experimental:_ Specifies the path in which to dump files when `com.mulesoft.dw.dump_files` is set to `true`.

* Type: `String`
* Default: `java.io.tmpdir` (system property value)

`com.mulesoft.dw.dump_folder` is an _experimental feature_ that is subject to change or removal from future versions of DataWeave. See xref:dataweave-troubleshoot.adoc[Troubleshooting a Failing DataWeave Script].


//com.mulesoft.dw.error_value_length//
|`com.mulesoft.dw.error_value_length`|
Sets the maximum length of exception messages to display to the user. The message is truncated to the maximum length. This setting is useful for avoiding long exception messages.

* Type: `Number`
* Default: `80`


//com.mulesoft.dw.indexsize//
|`com.mulesoft.dw.indexsize`|
Sets the maximum size (in bytes) of the page in memory that indexed readers use.

* Type: `Number`
* Default: `1572864` (1.5 MB)


//com.mulesoft.dw.max_memory_allocation//
|`com.mulesoft.dw.max_memory_allocation`|
Sets the size (in bytes) of each slot in the off-heap memory pool.

* Type: `Number` (in bytes)
* Default: `1572864` (1.5 MB)

See xref:dataweave-memory-management.adoc[DataWeave Memory Management].


//com.mulesoft.dw.memory_pool_size//
|`com.mulesoft.dw.memory_pool_size`|
Sets the number of slots in the memory pool. DataWeave buffers use off-heap memory from a pool, up to a defined size (`com.mulesoft.dw.memory_pool_size` * `com.mulesoft.dw.max_memory_allocation`). DataWeave allocates the remainder using heap memory. See xref:dataweave-memory-management.adoc[DataWeave Memory Management].

* Type: `Number`
* Default: `60`


//com.mulesoft.dw.multipart.defaultContentType//
|`com.mulesoft.dw.multipart.defaultContentType`|
Sets the default Content-Type to use on parts of the `multipart/*` format when a `Content-Type` is not specified. See also, the multipart reader property xref:dataweave-formats-multipart.adoc#properties[defaultContentType]. _Introduced in DataWeave 2.3 (2.3.0-20210720) for the August 2021 release of Mule 4.3.0-20210719._

* Type: `String`
* Default: `application/octet-stream`


//com.mulesoft.dw.valueSelector.selectsAlwaysFirst//
|`com.mulesoft.dw.valueSelector.selectsAlwaysFirst`|
When set to set to `true`, returns the first occurrence of an element (even if the element appears more than once). Enabling this behavior degrades performance.

* Type: `Boolean`
* Default: `false`

The following example illustrates the behavior that is controlled by this property. (Assume that the DataWeave script acts on the XML input.)

.XML input:
[source,xml,linenums]
----
<root>
  <users>
     <user>
       <lname>chibana</lname>
       <name>Shoki</name>
     </user>
     <user>
       <name>Shoki</name>
       <name>Tomo</name>
     </user>
  </users>
</root>
----

.DataWeave script:
[source,xml,linenums]
----
%dw 2.0
output application/json
---
{
    shokis: payload.root.users.*user map $.name
}
----

* If `com.mulesoft.dw.valueSelector.selectsAlwaysFirst` is set to `true`, the script returns the following output:
+
[source,json,linenums]
----
{
  "shokis": [
    "Shoki",
    "Shoki"
  ]
}
----

* If `com.mulesoft.dw.valueSelector.selectsAlwaysFirst` is set to `false`, the script returns the following output:
+
[source,json,linenums]
----
{
  "shokis": [
    "Shoki",
    "Tomo"
  ]
}
----


//com.mulesoft.dw.stacksize//
|`com.mulesoft.dw.stacksize`|
Sets the maximum size of the stack. When a function recurses too deeply, DataWeave throws an error, such as `Stack Overflow. Max stack is 256.`

* Type: `Number`
* Default: `256`


//com.mulesoft.dw.xml.supportDTD//
|`com.mulesoft.dw.xml.supportDTD`|
Controls whether DTD handling is enabled or disabled. When this property is set to `false`, DataWeaves skips processing of both internal and external subsets. Note that the default for this property changed from `true` to `false` in Mule version 4.3.0-20210427, which includes the May, 2021 patch of DataWeave version 2.3.0.

* Type: `Boolean`
* Default: `false`


//com.mulesoft.dw.track.cursor.close//
|`com.mulesoft.dw.track.cursor.close`|
When set to `true`, tracks the stack trace from which the `CursorProvider#close()` method is called.
Use this property for troubleshooting, for example, if `CursorProvider#openCursor()` is called on a cursor that is already closed.

* Type: `Boolean`
* Default: `false`


//com.mulesoft.dw.verbose//
|`com.mulesoft.dw.verbose`|
Displays filtered stack traces when this property is set to `true`. Does not display stack traces when set to `false`.

* Type: `Boolean`
* Default: `false`
|===
