= Map Objects
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, as


The following DataWeave examples use the `mapObject` function to iterate through the keys and values of objects.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

== First Example

This example uses both the `map` and `mapObject` functions to iterate through the input and set all of the keys to upper case.

The example uses these DataWeave functions:

* `map` to go through the elements in the "books" array.
* `mapObject` to go through the keys and values in each of the objects of the array.
* `upper` to set each key to upper case.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/map-an-object/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/map-an-object/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/map-an-object/out.json[]
----

== Second Example

This example uses the `mapObject` function to iterate through the keys and values of the object that results from using `groupBy` on the payload. If some objects of the input payload have the same values in the `FirstName`, `LastName` and `Age` keys, the DataWeave script transforms those objects into a single row in a CSV file. The remaining values in the `Team Name` and `Role` keys for those objects are concatenated with `:` in the single CSV row.

[[ex02]]

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/map-an-object-ex02/inputs/payload.json[]
----

In the previous input example, `Sr.No. 2` and `Sr.No. 3`, as well as `Sr.No. 5` and `Sr.No. 6`, refer to the same person, as they have the same first name, last name, and age. However, `Sr.No. 4` refers to a different person, as it has the same first and last name but a different age.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/map-an-object-ex02/transform.dwl[]
----

The DataWeave script merges the repeated values of keys `FirstName`, `LastName` and `Age` of the objects with key-value `Sr.No. 2` and `Sr.No. 3`, as well as `Sr.No. 5` and `Sr.No. 6`. These values are separated with `,` in the single CSV row. The values of `Team Name` and `Role` for those objects are concatenated with `:` in the single CSV row.

.Output CSV:
[source,CSV,linenums]
----
include::partial$cookbook-dw/map-an-object-ex02/out.csv[]
----


== Related Examples

* xref:dataweave-cookbook-map.adoc[Map Data with DataWeave]

* xref:dataweave-cookbook-map-object-elements-as-an-array.adoc[Map Object Elements as an Array]

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-perform-basic-transformation.adoc[Transform XML to JSON]

* xref:dataweave-cookbook-rename-keys.adoc[Rename Keys]

== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
