= DataFormat Types (dw::extension::DataFormat)

[%header, cols="1,2a,3a"]
|===
| Type | Definition | Description

| DataFormat
| `type DataFormat = { /**
* True if this is data format is represented as binary representation instead of text. False if not present.
**/
binaryFormat?: Boolean, /**
* Default character set of this format, if any.
**/
defaultCharset?: String, /**
* Returns the list of file extensions with the `.` &#40;for example, `.json`, `.xml`&#41; to assign to this data format.
**/
fileExtensions?: Array<String&#62;, /**
* The list of MIME types to accept.
**/
acceptedMimeTypes: Array<MimeType&#62;, /**
* Function that reads raw content and transforms it into the canonical DataWeave model.
**/
reader: &#40;content: Binary, charset: String, settings: ReaderSettings&#41; &#45;&#62; Any, /**
* Function that writes the canonical DataWeave model into binary content.
**/
writer: &#40;value: Any, settings: WriterSettings&#41; &#45;&#62; Binary }`
| Represents the DataFormat definition.

_Introduced in DataWeave version 2.2.0._


| EmptySettings
| `type EmptySettings = Object`
| Represents a configuration with no settings.

_Introduced in DataWeave version 2.2.0._


| EncodingSettings
| `type EncodingSettings = { /**
* Encoding that the writer uses for output. Defaults to "UTF&#45;8".
**/
encoding?: String {defaultValue: "UTF&#45;8"} }`
| Represents encoding settings.

_Introduced in DataWeave version 2.2.0._


| MimeType
| `type MimeType = String`
| Represents a MIME type, such as `application/json`.

_Introduced in DataWeave version 2.2.0._


| Settings
| `type Settings = Object`
| Reader or writer configuration settings.

_Introduced in DataWeave version 2.2.0._

|===
