= DataFormat Types (dw::extension::DataFormat)

|===
| Type | Definition | Description

| DataFormat
| `type DataFormat = { /**
* True if this is data format is represented in a binary representation instead of text, if not present is false
**/
binaryFormat?: Boolean, /**
* The default charset of this format, if any.
**/
defaultCharset?: String, /**
* Returns the list of file extensions with the . &#40;".json", ".xml", etc...&#41; that should be assigned to this Data Format
**/
fileExtensions?: Array<String&#62;, /**
* The list of MimeTypes that are accepted
**/
acceptedMimeTypes: Array<MimeType&#62;, /**
* This function will be in charge of reading the raw content and transform it into the DW canonical model
**/
reader: &#40;content: Binary, charset: String, settings: ReaderSettings&#41; &#45;&#62; Any, /**
* This function will be in charge of writing the DW canonical model into Binary content
**/
writer: &#40;value: Any, settings: WriterSettings&#41; &#45;&#62; Binary }`
| Represents the DataFormat definition.

_Introduced in DataWeave version 2.2.0._


| EmptySettings
| `type EmptySettings = Object`
| Represents a configuration with no Settings.

_Introduced in DataWeave version 2.2.0._


| EncodingSettings
| `type EncodingSettings = { /**
* The character set to use for the output, such as UTF&#45;8.
**/
encoding?: String {defaultValue: "UTF&#45;8"} }`
| Represents an Encoding Settings.

_Introduced in DataWeave version 2.2.0._


| MimeType
| `type MimeType = String`
| Represents a MimeType, such as `application/json`.

_Introduced in DataWeave version 2.2.0._


| Settings
| `type Settings = Object`
| Represents reader or writer configuration Settings.

_Introduced in DataWeave version 2.2.0._

|===