= localDateTime
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[localdatetime1]]
== localDateTime&#40;parts: LocalDateTimeFactory&#41;: LocalDateTime

Creates a `LocalDateTime` value from values specified for `year`, `month`, `day`,
`hour`, `minutes`, and `seconds` fields.

_Introduced in DataWeave version 2.4.0._

=== Parameters

[%header, cols="1,3a"]
|===
| Name | Description
| `parts` | `Number` values for `year`, `month`, `day`, `hour`, `minutes`, and
          `seconds` fields. Valid values are numbers between 1 and 12 for the
          `month`, 1 through 31 for the `day`, 0 through 23 for the `hour`,
          0 through 59 for `minutes`, and 0 through 59 (including decimals, such as 59.99) for `seconds` fields.
          You can specify the name-value pairs in any order,
          but the output is ordered as a default `LocalDateTime` value,
          such as `2012-10-11T10:10:10`. The input fields are parts of
          a `LocalDateTimeFactory` type.
|===

=== Example

This example shows how to create a value of type `LocalDateTime`.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
    newLocalDateTime: localDateTime({year: 2012, month: 10, day: 11, hour: 12, minutes: 30, seconds: 40})
}
----

==== Output

[source,Json,linenums]
----
{
   "newLocalDateTime": "2012-10-11T12:30:40"
}
----

