= Runtime Types (dw::Runtime)

|===
| Type | Definition | Description

| DataFormatDescriptor
| `type DataFormatDescriptor = { name: String, binary: Boolean, defaultEncoding?: String, extensions: Array<String&#62;, defaultMimeType: String, acceptedMimeTypes: Array<String&#62;, readerProperties: Array<DataFormatProperty&#62;, writerProperties: Array<DataFormatProperty&#62; }`
| Description of a `DataFormat` that provides all metadata information.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| DataFormatProperty
| `type DataFormatProperty = { name: String, optional: Boolean, defaultValue?: Any, description: String, possibleValues: Array<Any&#62; }`
| Type that describes a data format property. The fields include a `name`,
`description`, array of possible values (`possibleValues`), an optional default
value (`defaultValue`), and  an `optional` flag that indicates whether the property 
is required or not.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| EvalSuccess
| `type EvalSuccess = { success: true, value: Any, logs: Array<LogEntry&#62; }`
| Data type of the data that returns when an `eval` function executes successfully.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| ExecutionFailure
| `type ExecutionFailure = { success: false, message: String, kind: String, stack?: Array<String&#62;, location: Location, logs: Array<LogEntry&#62; }`
| Data type of the data that returns when a `run` or `eval` function fails.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| Location
| `type Location = { start?: Position, end?: Position, locationString: String, text?: String, sourceIdentifier?: String }`
| Type that represents the location of an expression in a DataWeave file.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| LogEntry
| `type LogEntry = { level: LogLevel, timestamp: String, message: String }`
| Type for a log entry, which consists of a `level` for a `LogLevel` value,
a `timestamp`, and `message`.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| LogLevel
| `type LogLevel = "INFO" &#124; "ERROR" &#124; "WARN"`
| Identifies the different kinds of log levels (`INFO`, `ERROR`, or `WARN`).

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| LoggerService
| `type LoggerService = { /**
* Function called when the execution starts. DataWeave sends the result
* to every `log` call through the `context` parameter, so that, for example,
* a logging header can be sent at initialization and recovered in each log.
**/
initialize?: &#40;&#41; &#45;&#62; Object, /**
* Function that is called on every log message.
**/
log: &#40;level: LogLevel, msg: String, context: Object&#41; &#45;&#62; Any, /**
* Function called when the execution completes, which is a common time
* to flush any buffer or to log out gracefully.
**/
shutdown?: &#40;&#41; &#45;&#62; Boolean }`
| Service that handles all logging.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| MimeType
| `type MimeType = String`
| A String representation of a MIME type.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| Position
| `type Position = { index: Number, line: Number, column: Number }`
| Type that represents a position in a file by its index and its line and column.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| ReaderInput
| `type ReaderInput = { /**
* The input, in Binary format.
**/
value: Binary, /**
* The encoding for the reader to use.
**/
encoding?: String, /**
* The reader properties used to parse the input.
**/
properties?: Dictionary<SimpleType&#62;, /**
* The MIME type of the input.
**/
mimeType: MimeType }`
| Input to the DataWeave reader created for the specified MIME type, which includes 
the Binary input and MIME type, as well as optional encoding and properties values.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| RunSuccess
| `type RunSuccess = { success: true, value: Binary, mimeType: MimeType, encoding?: String, logs: Array<LogEntry&#62; }`
| Data type of the data that returns when a `run` function executes successfully.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| RuntimeExecutionConfiguration
| `type RuntimeExecutionConfiguration = { /**
* Maximum amount of time the DataWeave script takes before timing out.
**/
timeOut?: Number, /**
* Default output MIME type if not specified in the DataWeave script.
**/
outputMimeType?: MimeType, /**
* Writer properties to use with the specified the `outputMimeType` property.
**/
writerProperties?: Dictionary<SimpleType&#62;, /**
* Specifies the behavior that occurs when the execution fails:
* 
* * `HANDLE` &#40;default value&#41; returns `ExecutionFailure`.
* * `FAIL` propagates an exception.
**/
onException?: "HANDLE" &#124; "FAIL", /**
* Identifies the `SecurityManager` to use in this execution. This security manager
* is composed by the current `SecurityManager`.
**/
securityManager?: SecurityManager, /**
* The `LoggerService` to use in this execution.
**/
loggerService?: LoggerService, /**
* The maximum stack size.
**/
maxStackSize?: Number, /**
* Callback that is called when the watchdog was not able to stop the execution after a timeout.
*  Is useful for logging or reporting the problem.
* 
*  The callback is going to be called with :
*  * threadName: The Thread name that is hanged
*  * javaStackTrace: The javaStackTrace where it is hanged
*  * code: The DW Code that caused this being hanged
**/
onUnhandledTimeout?: &#40;threadName: String, javaStackTrace: String, code: String&#41; &#45;&#62; Any }`
| Configuration of the runtime execution that has advanced parameters.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| SecurityManager
| `type SecurityManager = &#40;grant: String, args: Array<Any&#62;&#41; &#45;&#62; Boolean`
| Function that is called when a privilege must be granted to the current execution.

* `grant` is the name of the privilege, such as `Resource`.
* `args` provides a list of parameters that the function requesting the privilege calls.

_Experimental_: This type is an experimental feature that is subject to change or removal from future versions of DataWeave


| TryResult
| `type TryResult = { success: Boolean, result?: T, error?: { kind: String, message: String, stack?: Array<String&#62;, /**
* Since 4.4.0. It is only available when stack is not present. It will contain the native java stacktrace.
**/
stackTrace?: String, location?: String } }`
| Object with a result or error message. If `success` is `false`, data type provides
the `error`. If `true`, the data type provides the `result`.

|===
