= DataWeave Language
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datawave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping
:page-aliases: 4.3@mule-runtime::dataweave.adoc

include::partial$dataweave-intro.adoc[]

You write DataWeave expressions and scripts within message processors (components, connectors, or modules) when creating apps in Anypoint Studio or Design Center, or as handwritten XML configuration files.

DataWeave 2.3 is compatible and bundles with Mule runtime version 4.3.

* To get started with DataWeave version 2 for Mule runtime engine (Mule) version 4 visit
xref:dataweave-quickstart.adoc[the quickstart].
* To learn about DataWeave version 2 for Mule version 4, visit xref:dataweave-language-guide.adoc[the language guide].
* To look up reference information about DataWeave version 2 operators and functions, visit xref:dw-functions.adoc[the reference guide].
* To find information about DataWeave version 1 for Mule 3.9 and earlier, visit xref:3.9@mule-runtime::dataweave.adoc[the DataWeave version 1 documentation].

NOTE: In the Mule 4.2 release, DataWeave 2.2 introduces a number
of functions, types, and annotations that are not supported by Mule 4.1. Within
the DataWeave Reference, these items are tagged with the following text:
_Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._
