= What's New in DataWeave

TODO

* Function signatures provide more detail
* Addition of many functions to handle null values
* DW modules in the TOC/left-nav are reorganized alphabetically using the module names (such as dw::Core, dw::core::Arrays, dw::module::Multipart, etc.) vs Core (dw::Core), Arrays(dw::core::Arrays), etc.)

* Experimental features in the following. files:
	modified:   dw-core-annotations.adoc
	modified:   dw-runtime-functions-dataformatsdescriptor.adoc
	modified:   dw-runtime-functions-eval.adoc
	modified:   dw-runtime-functions-evalurl.adoc
	modified:   dw-runtime-functions-run.adoc
	modified:   dw-runtime-functions-runurl.adoc


== TODO: New DataWeave Modules, Functions, Types, Annotations, etc.

TODO: NEW FROM COERCIONS
* NEW: ../dw-coercions-functions-toarray.adoc
* NEW: ../dw-coercions-functions-tobinary.adoc
* NEW: ../dw-coercions-functions-toboolean.adoc
* NEW: ../dw-coercions-functions-todate.adoc
* NEW: ../dw-coercions-functions-todatetime.adoc
* NEW: ../dw-coercions-functions-tolocaldatetime.adoc
* NEW: ../dw-coercions-functions-tolocaltime.adoc
* NEW: ../dw-coercions-functions-tonumber.adoc
* NEW: ../dw-coercions-functions-toperiod.adoc
* NEW: ../dw-coercions-functions-toregex.adoc
* NEW: ../dw-coercions-functions-tostring.adoc
* NEW: ../dw-coercions-functions-totime.adoc
* NEW: ../dw-coercions-functions-totimezone.adoc
* NEW: ../dw-coercions-functions-touri.adoc
* NEW: ../dw-coercions-types.adoc
* NEW: ../dw-coercions.adoc

//TODO: NEW FROM CORE
* NEW: ../dw-core-functions-indexof.adoc
* NEW: ../dw-core-functions-lastindexof.adoc
* NEW: ../dw-core-functions-onnull.adoc
* NEW: ../dw-core-functions-then.adoc

//TODO: DATES IS NEW
* NEW: ../dw-dates-functions-atbeginningofday.adoc
* NEW: ../dw-dates-functions-atbeginningofhour.adoc
* NEW: ../dw-dates-functions-atbeginningofmonth.adoc
* NEW: ../dw-dates-functions-atbeginningofweek.adoc
* NEW: ../dw-dates-functions-atbeginningofyear.adoc
* NEW: ../dw-dates-functions-date.adoc
* NEW: ../dw-dates-functions-datetime.adoc
* NEW: ../dw-dates-functions-localdatetime.adoc
* NEW: ../dw-dates-functions-localtime.adoc
* NEW: ../dw-dates-functions-time.adoc
* NEW: ../dw-dates-functions-today.adoc
* NEW: ../dw-dates-functions-tomorrow.adoc
* NEW: ../dw-dates-functions-yesterday.adoc
* NEW: ../dw-dates-types.adoc
* NEW: ../dw-dates.adoc

//TODO: MATH IS NEW
* NEW: ../dw-math-functions-acos.adoc
* NEW: ../dw-math-functions-asin.adoc
* NEW: ../dw-math-functions-atan.adoc
* NEW: ../dw-math-functions-cos.adoc
* NEW: ../dw-math-functions-log10.adoc
* NEW: ../dw-math-functions-logn.adoc
* NEW: ../dw-math-functions-sin.adoc
* NEW: ../dw-math-functions-tan.adoc
* NEW: ../dw-math-functions-todegrees.adoc
* NEW: ../dw-math-functions-toradians.adoc
* NEW: ../dw-math-variables.adoc
* NEW: ../dw-math.adoc

//TODO: PERIODS IS NEW
* NEW: ../dw-periods-functions-between.adoc
* NEW: ../dw-periods-functions-days.adoc
* NEW: ../dw-periods-functions-duration.adoc
* NEW: ../dw-periods-functions-hours.adoc
* NEW: ../dw-periods-functions-minutes.adoc
* NEW: ../dw-periods-functions-months.adoc
* NEW: ../dw-periods-functions-period.adoc
* NEW: ../dw-periods-functions-seconds.adoc
* NEW: ../dw-periods-functions-years.adoc
* NEW: ../dw-periods.adoc

//TODO: NEW IN RUNTIME
* NEW: ../dw-runtime-functions-dataformatsdescriptor.adoc
* NEW: ../dw-runtime-functions-eval.adoc
* NEW: ../dw-runtime-functions-evalurl.adoc
* NEW: ../dw-runtime-functions-run.adoc
* NEW: ../dw-runtime-functions-runurl.adoc

//TODO: NEW IN STRINGS
* NEW: ../dw-strings-functions-collapse.adoc
* NEW: ../dw-strings-functions-countcharactersby.adoc
* NEW: ../dw-strings-functions-countmatches.adoc
* NEW: ../dw-strings-functions-everycharacter.adoc
* NEW: ../dw-strings-functions-first.adoc
* NEW: ../dw-strings-functions-hammingdistance.adoc
* NEW: ../dw-strings-functions-last.adoc
* NEW: ../dw-strings-functions-levenshteindistance.adoc
* NEW: ../dw-strings-functions-lines.adoc
* NEW: ../dw-strings-functions-mapstring.adoc
* NEW: ../dw-strings-functions-remove.adoc
* NEW: ../dw-strings-functions-replaceall.adoc
* NEW: ../dw-strings-functions-reverse.adoc
* NEW: ../dw-strings-functions-somecharacter.adoc
* NEW: ../dw-strings-functions-substring.adoc
* NEW: ../dw-strings-functions-substringby.adoc
* NEW: ../dw-strings-functions-substringevery.adoc
* NEW: ../dw-strings-functions-words.adoc

//TODO: NEW IN TREE
* NEW: ../dw-tree-functions-filterarrayleafs.adoc
* NEW: ../dw-tree-functions-filterobjectleafs.adoc
* NEW: ../dw-tree-functions-filtertree.adoc
* NEW: ../dw-tree-functions-isarraytype.adoc
* NEW: ../dw-tree-functions-isattributetype.adoc
* NEW: ../dw-tree-functions-isobjecttype.adoc

//TODO: NEW IN VALUES
* NEW: ../dw-values-types.adoc


TODO: MODIFIED IN 2.4 (SOME MODS DUE TO FUNCTION SIG IMPROVEMENTS AND DON'T NEED SPECIAL MENTION)

* modified:   ../dw-arrays-functions-countby.adoc
* modified:   ../dw-arrays-functions-divideby.adoc
* modified:   ../dw-arrays-functions-drop.adoc
* modified:   ../dw-arrays-functions-dropwhile.adoc
* modified:   ../dw-arrays-functions-every.adoc
* modified:   ../dw-arrays-functions-firstwith.adoc
* modified:   ../dw-arrays-functions-indexof.adoc
* modified:   ../dw-arrays-functions-indexwhere.adoc
* modified:   ../dw-arrays-functions-join.adoc
* modified:   ../dw-arrays-functions-leftjoin.adoc
* modified:   ../dw-arrays-functions-outerjoin.adoc
* modified:   ../dw-arrays-functions-partition.adoc
* modified:   ../dw-arrays-functions-slice.adoc
* modified:   ../dw-arrays-functions-some.adoc
* modified:   ../dw-arrays-functions-splitat.adoc
* modified:   ../dw-arrays-functions-splitwhere.adoc
* modified:   ../dw-arrays-functions-sumby.adoc
* modified:   ../dw-arrays-functions-take.adoc
* modified:   ../dw-arrays-functions-takewhile.adoc
* modified:   ../dw-arrays.adoc
* modified:   ../dw-binaries-functions-frombase64.adoc
* modified:   ../dw-binaries-functions-fromhex.adoc
* modified:   ../dw-binaries-functions-readlineswith.adoc
* modified:   ../dw-binaries-functions-tobase64.adoc
* modified:   ../dw-binaries-functions-tohex.adoc
* modified:   ../dw-binaries-functions-writelineswith.adoc
* modified:   ../dw-binaries.adoc
* modified:   ../dw-core-annotations.adoc
* modified:   ../dw-core-functions-abs.adoc
* modified:   ../dw-core-functions-avg.adoc
* modified:   ../dw-core-functions-ceil.adoc
* modified:   ../dw-core-functions-contains.adoc
* modified:   ../dw-core-functions-daysbetween.adoc
* modified:   ../dw-core-functions-distinctby.adoc
* modified:   ../dw-core-functions-endswith.adoc
* modified:   ../dw-core-functions-entriesof.adoc
* modified:   ../dw-core-functions-filter.adoc
* modified:   ../dw-core-functions-filterobject.adoc
* modified:   ../dw-core-functions-find.adoc
* modified:   ../dw-core-functions-flatmap.adoc
* modified:   ../dw-core-functions-flatten.adoc
* modified:   ../dw-core-functions-floor.adoc
* modified:   ../dw-core-functions-groupby.adoc
* modified:   ../dw-core-functions-isblank.adoc
* modified:   ../dw-core-functions-isdecimal.adoc
* modified:   ../dw-core-functions-isempty.adoc
* modified:   ../dw-core-functions-iseven.adoc
* modified:   ../dw-core-functions-isinteger.adoc
* modified:   ../dw-core-functions-isleapyear.adoc
* modified:   ../dw-core-functions-isodd.adoc
* modified:   ../dw-core-functions-joinby.adoc
* modified:   ../dw-core-functions-keysof.adoc
* modified:   ../dw-core-functions-log.adoc
* modified:   ../dw-core-functions-lower.adoc
* modified:   ../dw-core-functions-map.adoc
* modified:   ../dw-core-functions-mapobject.adoc
* modified:   ../dw-core-functions-match.adoc
* modified:   ../dw-core-functions-matches.adoc
* modified:   ../dw-core-functions-max.adoc
* modified:   ../dw-core-functions-maxby.adoc
* modified:   ../dw-core-functions-min.adoc
* modified:   ../dw-core-functions-minby.adoc
* modified:   ../dw-core-functions-minusminus.adoc
* modified:   ../dw-core-functions-mod.adoc
* modified:   ../dw-core-functions-namesof.adoc
* modified:   ../dw-core-functions-now.adoc
* modified:   ../dw-core-functions-orderby.adoc
* modified:   ../dw-core-functions-pluck.adoc
* modified:   ../dw-core-functions-plusplus.adoc
* modified:   ../dw-core-functions-pow.adoc
* modified:   ../dw-core-functions-random.adoc
* modified:   ../dw-core-functions-randomint.adoc
* modified:   ../dw-core-functions-read.adoc
* modified:   ../dw-core-functions-readurl.adoc
* modified:   ../dw-core-functions-reduce.adoc
* modified:   ../dw-core-functions-replace.adoc
* modified:   ../dw-core-functions-round.adoc
* modified:   ../dw-core-functions-scan.adoc
* modified:   ../dw-core-functions-sizeof.adoc
* modified:   ../dw-core-functions-splitby.adoc
* modified:   ../dw-core-functions-sqrt.adoc
* modified:   ../dw-core-functions-startswith.adoc
* modified:   ../dw-core-functions-sum.adoc
* modified:   ../dw-core-functions-to.adoc
* modified:   ../dw-core-functions-trim.adoc
* modified:   ../dw-core-functions-typeof.adoc
* modified:   ../dw-core-functions-unzip.adoc
* modified:   ../dw-core-functions-upper.adoc
* modified:   ../dw-core-functions-uuid.adoc
* modified:   ../dw-core-functions-valuesof.adoc
* modified:   ../dw-core-functions-with.adoc
* modified:   ../dw-core-functions-write.adoc
* modified:   ../dw-core-functions-xsitype.adoc
* modified:   ../dw-core-functions-zip.adoc
* modified:   ../dw-core-namespaces.adoc
* modified:   ../dw-core-types.adoc
* modified:   ../dw-core.adoc
* modified:   ../dw-crypto-functions-hashwith.adoc
* modified:   ../dw-crypto-functions-hmacbinary.adoc
* modified:   ../dw-crypto-functions-hmacwith.adoc
* modified:   ../dw-crypto-functions-md5.adoc
* modified:   ../dw-crypto-functions-sha1.adoc
* modified:   ../dw-crypto.adoc
* modified:   ../dw-dataformat-annotations.adoc
* modified:   ../dw-dataformat-types.adoc
* modified:   ../dw-dataformat.adoc
* modified:   ../dw-diff-functions-diff.adoc
* modified:   ../dw-diff-types.adoc
* modified:   ../dw-diff.adoc
* modified:   ../dw-mule-functions-causedby.adoc
* modified:   ../dw-mule-functions-lookup.adoc
* modified:   ../dw-mule-functions-p.adoc
* modified:   ../dw-mule-types.adoc
* modified:   ../dw-mule.adoc
* modified:   ../dw-multipart-functions-field.adoc
* modified:   ../dw-multipart-functions-file.adoc
* modified:   ../dw-multipart-functions-form.adoc
* modified:   ../dw-multipart-functions-generateboundary.adoc
* modified:   ../dw-multipart-types.adoc
* modified:   ../dw-multipart.adoc
* modified:   ../dw-numbers-functions-frombinary.adoc
* modified:   ../dw-numbers-functions-fromhex.adoc
* modified:   ../dw-numbers-functions-fromradixnumber.adoc
* modified:   ../dw-numbers-functions-tobinary.adoc
* modified:   ../dw-numbers-functions-tohex.adoc
* modified:   ../dw-numbers-functions-toradixnumber.adoc
* modified:   ../dw-numbers.adoc
* modified:   ../dw-objects-functions-divideby.adoc
* modified:   ../dw-objects-functions-entryset.adoc
* modified:   ../dw-objects-functions-everyentry.adoc
* modified:   ../dw-objects-functions-keyset.adoc
* modified:   ../dw-objects-functions-mergewith.adoc
* modified:   ../dw-objects-functions-nameset.adoc
* modified:   ../dw-objects-functions-someentry.adoc
* modified:   ../dw-objects-functions-takewhile.adoc
* modified:   ../dw-objects-functions-valueset.adoc
* modified:   ../dw-objects.adoc
* modified:   ../dw-runtime-functions-fail.adoc
* modified:   ../dw-runtime-functions-failif.adoc
* modified:   ../dw-runtime-functions-locationstring.adoc
* modified:   ../dw-runtime-functions-orelse.adoc
* modified:   ../dw-runtime-functions-orelsetry.adoc
* modified:   ../dw-runtime-functions-prop.adoc
* modified:   ../dw-runtime-functions-props.adoc
* modified:   ../dw-runtime-functions-try.adoc
* modified:   ../dw-runtime-functions-wait.adoc
* modified:   ../dw-runtime-types.adoc
* modified:   ../dw-runtime.adoc
* modified:   ../dw-strings-functions-appendifmissing.adoc
* modified:   ../dw-strings-functions-camelize.adoc
* modified:   ../dw-strings-functions-capitalize.adoc
* modified:   ../dw-strings-functions-charcode.adoc
* modified:   ../dw-strings-functions-charcodeat.adoc
* modified:   ../dw-strings-functions-dasherize.adoc
* modified:   ../dw-strings-functions-fromcharcode.adoc
* modified:   ../dw-strings-functions-isalpha.adoc
* modified:   ../dw-strings-functions-isalphanumeric.adoc
* modified:   ../dw-strings-functions-islowercase.adoc
* modified:   ../dw-strings-functions-isnumeric.adoc
* modified:   ../dw-strings-functions-isuppercase.adoc
* modified:   ../dw-strings-functions-iswhitespace.adoc
* modified:   ../dw-strings-functions-leftpad.adoc
* modified:   ../dw-strings-functions-ordinalize.adoc
* modified:   ../dw-strings-functions-pluralize.adoc
* modified:   ../dw-strings-functions-prependifmissing.adoc
* modified:   ../dw-strings-functions-repeat.adoc
* modified:   ../dw-strings-functions-rightpad.adoc
* modified:   ../dw-strings-functions-singularize.adoc
* modified:   ../dw-strings-functions-substringafter.adoc
* modified:   ../dw-strings-functions-substringafterlast.adoc
* modified:   ../dw-strings-functions-substringbefore.adoc
* modified:   ../dw-strings-functions-substringbeforelast.adoc
* modified:   ../dw-strings-functions-underscore.adoc
* modified:   ../dw-strings-functions-unwrap.adoc
* modified:   ../dw-strings-functions-withmaxsize.adoc
* modified:   ../dw-strings-functions-wrapifmissing.adoc
* modified:   ../dw-strings-functions-wrapwith.adoc
* modified:   ../dw-strings.adoc
* modified:   ../dw-system-functions-envvar.adoc
* modified:   ../dw-system-functions-envvars.adoc
* modified:   ../dw-system.adoc
* modified:   ../dw-timer-functions-currentmilliseconds.adoc
* modified:   ../dw-timer-functions-duration.adoc
* modified:   ../dw-timer-functions-time.adoc
* modified:   ../dw-timer-functions-tomilliseconds.adoc
* modified:   ../dw-timer-types.adoc
* modified:   ../dw-timer.adoc
* modified:   ../dw-tree-functions-asexpressionstring.adoc
* modified:   ../dw-tree-functions-mapleafvalues.adoc
* modified:   ../dw-tree-functions-nodeexists.adoc
* modified:   ../dw-tree-types.adoc
* modified:   ../dw-tree-variables.adoc
* modified:   ../dw-tree.adoc
* modified:   ../dw-types-functions-arrayitem.adoc
* modified:   ../dw-types-functions-basetypeof.adoc
* modified:   ../dw-types-functions-functionparamtypes.adoc
* modified:   ../dw-types-functions-functionreturntype.adoc
* modified:   ../dw-types-functions-intersectionitems.adoc
* modified:   ../dw-types-functions-isanytype.adoc
* modified:   ../dw-types-functions-isarraytype.adoc
* modified:   ../dw-types-functions-isbinarytype.adoc
* modified:   ../dw-types-functions-isbooleantype.adoc
* modified:   ../dw-types-functions-isdatetimetype.adoc
* modified:   ../dw-types-functions-isdatetype.adoc
* modified:   ../dw-types-functions-isfunctiontype.adoc
* modified:   ../dw-types-functions-isintersectiontype.adoc
* modified:   ../dw-types-functions-iskeytype.adoc
* modified:   ../dw-types-functions-isliteraltype.adoc
* modified:   ../dw-types-functions-islocaldatetimetype.adoc
* modified:   ../dw-types-functions-islocaltimetype.adoc
* modified:   ../dw-types-functions-isnamespacetype.adoc
* modified:   ../dw-types-functions-isnothingtype.adoc
* modified:   ../dw-types-functions-isnulltype.adoc
* modified:   ../dw-types-functions-isnumbertype.adoc
* modified:   ../dw-types-functions-isobjecttype.adoc
* modified:   ../dw-types-functions-isperiodtype.adoc
* modified:   ../dw-types-functions-israngetype.adoc
* modified:   ../dw-types-functions-isreferencetype.adoc
* modified:   ../dw-types-functions-isregextype.adoc
* modified:   ../dw-types-functions-isstringtype.adoc
* modified:   ../dw-types-functions-istimetype.adoc
* modified:   ../dw-types-functions-istimezonetype.adoc
* modified:   ../dw-types-functions-istypetype.adoc
* modified:   ../dw-types-functions-isuniontype.adoc
* modified:   ../dw-types-functions-isuritype.adoc
* modified:   ../dw-types-functions-literalvalueof.adoc
* modified:   ../dw-types-functions-metadataof.adoc
* modified:   ../dw-types-functions-nameof.adoc
* modified:   ../dw-types-functions-objectfields.adoc
* modified:   ../dw-types-functions-unionitems.adoc
* modified:   ../dw-types-types.adoc
* modified:   ../dw-types.adoc
* modified:   ../dw-url-functions-compose.adoc
* modified:   ../dw-url-functions-decodeuri.adoc
* modified:   ../dw-url-functions-decodeuricomponent.adoc
* modified:   ../dw-url-functions-encodeuri.adoc
* modified:   ../dw-url-functions-encodeuricomponent.adoc
* modified:   ../dw-url-functions-parseuri.adoc
* modified:   ../dw-url-types.adoc
* modified:   ../dw-url.adoc
* modified:   ../dw-values-functions-attr.adoc
* modified:   ../dw-values-functions-field.adoc
* modified:   ../dw-values-functions-index.adoc
* modified:   ../dw-values-functions-mask.adoc
* modified:   ../dw-values-functions-update.adoc
* modified:   ../dw-values.adoc


////
modified:   _partials/nav-dw.adoc
modified:   dw-arrays-functions-countby.adoc
modified:   dw-arrays-functions-divideby.adoc
modified:   dw-arrays-functions-drop.adoc
modified:   dw-arrays-functions-dropwhile.adoc
modified:   dw-arrays-functions-every.adoc
modified:   dw-arrays-functions-firstwith.adoc
modified:   dw-arrays-functions-indexof.adoc
modified:   dw-arrays-functions-indexwhere.adoc
modified:   dw-arrays-functions-join.adoc
modified:   dw-arrays-functions-leftjoin.adoc
modified:   dw-arrays-functions-outerjoin.adoc
modified:   dw-arrays-functions-partition.adoc
modified:   dw-arrays-functions-slice.adoc
modified:   dw-arrays-functions-some.adoc
modified:   dw-arrays-functions-splitat.adoc
modified:   dw-arrays-functions-splitwhere.adoc
modified:   dw-arrays-functions-sumby.adoc
modified:   dw-arrays-functions-take.adoc
modified:   dw-arrays-functions-takewhile.adoc
modified:   dw-arrays.adoc
modified:   dw-binaries-functions-frombase64.adoc
modified:   dw-binaries-functions-fromhex.adoc
modified:   dw-binaries-functions-readlineswith.adoc
modified:   dw-binaries-functions-tobase64.adoc
modified:   dw-binaries-functions-tohex.adoc
modified:   dw-binaries-functions-writelineswith.adoc
modified:   dw-binaries.adoc
new file:   dw-coercions-functions-toarray.adoc
new file:   dw-coercions-functions-tobinary.adoc
new file:   dw-coercions-functions-toboolean.adoc
new file:   dw-coercions-functions-todate.adoc
new file:   dw-coercions-functions-todatetime.adoc
new file:   dw-coercions-functions-tolocaldatetime.adoc
new file:   dw-coercions-functions-tolocaltime.adoc
new file:   dw-coercions-functions-tonumber.adoc
new file:   dw-coercions-functions-toperiod.adoc
new file:   dw-coercions-functions-toregex.adoc
new file:   dw-coercions-functions-tostring.adoc
new file:   dw-coercions-functions-totime.adoc
new file:   dw-coercions-functions-totimezone.adoc
new file:   dw-coercions-functions-touri.adoc
new file:   dw-coercions-types.adoc
new file:   dw-coercions.adoc
modified:   dw-core-annotations.adoc
modified:   dw-core-functions-abs.adoc
modified:   dw-core-functions-avg.adoc
modified:   dw-core-functions-ceil.adoc
modified:   dw-core-functions-contains.adoc
modified:   dw-core-functions-daysbetween.adoc
modified:   dw-core-functions-distinctby.adoc
modified:   dw-core-functions-endswith.adoc
modified:   dw-core-functions-entriesof.adoc
modified:   dw-core-functions-filter.adoc
modified:   dw-core-functions-filterobject.adoc
modified:   dw-core-functions-find.adoc
modified:   dw-core-functions-flatmap.adoc
modified:   dw-core-functions-flatten.adoc
modified:   dw-core-functions-floor.adoc
modified:   dw-core-functions-groupby.adoc
new file:   dw-core-functions-indexof.adoc
modified:   dw-core-functions-isblank.adoc
modified:   dw-core-functions-isdecimal.adoc
modified:   dw-core-functions-isempty.adoc
modified:   dw-core-functions-iseven.adoc
modified:   dw-core-functions-isinteger.adoc
modified:   dw-core-functions-isleapyear.adoc
modified:   dw-core-functions-isodd.adoc
modified:   dw-core-functions-joinby.adoc
modified:   dw-core-functions-keysof.adoc
new file:   dw-core-functions-lastindexof.adoc
modified:   dw-core-functions-log.adoc
modified:   dw-core-functions-lower.adoc
modified:   dw-core-functions-map.adoc
modified:   dw-core-functions-mapobject.adoc
modified:   dw-core-functions-match.adoc
modified:   dw-core-functions-matches.adoc
modified:   dw-core-functions-max.adoc
modified:   dw-core-functions-maxby.adoc
modified:   dw-core-functions-min.adoc
modified:   dw-core-functions-minby.adoc
modified:   dw-core-functions-minusminus.adoc
modified:   dw-core-functions-mod.adoc
modified:   dw-core-functions-namesof.adoc
modified:   dw-core-functions-now.adoc
new file:   dw-core-functions-onnull.adoc
modified:   dw-core-functions-orderby.adoc
modified:   dw-core-functions-pluck.adoc
modified:   dw-core-functions-plusplus.adoc
modified:   dw-core-functions-pow.adoc
modified:   dw-core-functions-random.adoc
modified:   dw-core-functions-randomint.adoc
modified:   dw-core-functions-read.adoc
modified:   dw-core-functions-readurl.adoc
modified:   dw-core-functions-reduce.adoc
modified:   dw-core-functions-replace.adoc
modified:   dw-core-functions-round.adoc
modified:   dw-core-functions-scan.adoc
modified:   dw-core-functions-sizeof.adoc
modified:   dw-core-functions-splitby.adoc
modified:   dw-core-functions-sqrt.adoc
modified:   dw-core-functions-startswith.adoc
modified:   dw-core-functions-sum.adoc
new file:   dw-core-functions-then.adoc
modified:   dw-core-functions-to.adoc
modified:   dw-core-functions-trim.adoc
modified:   dw-core-functions-typeof.adoc
modified:   dw-core-functions-unzip.adoc
modified:   dw-core-functions-upper.adoc
modified:   dw-core-functions-uuid.adoc
modified:   dw-core-functions-valuesof.adoc
modified:   dw-core-functions-with.adoc
modified:   dw-core-functions-write.adoc
modified:   dw-core-functions-xsitype.adoc
modified:   dw-core-functions-zip.adoc
modified:   dw-core-namespaces.adoc
modified:   dw-core-types.adoc
modified:   dw-core.adoc
modified:   dw-crypto-functions-hashwith.adoc
modified:   dw-crypto-functions-hmacbinary.adoc
modified:   dw-crypto-functions-hmacwith.adoc
modified:   dw-crypto-functions-md5.adoc
modified:   dw-crypto-functions-sha1.adoc
modified:   dw-crypto.adoc
modified:   dw-dataformat-annotations.adoc
modified:   dw-dataformat-types.adoc
modified:   dw-dataformat.adoc
new file:   dw-dates-functions-atbeginningofday.adoc
new file:   dw-dates-functions-atbeginningofhour.adoc
new file:   dw-dates-functions-atbeginningofmonth.adoc
new file:   dw-dates-functions-atbeginningofweek.adoc
new file:   dw-dates-functions-atbeginningofyear.adoc
new file:   dw-dates-functions-date.adoc
new file:   dw-dates-functions-datetime.adoc
new file:   dw-dates-functions-localdatetime.adoc
new file:   dw-dates-functions-localtime.adoc
new file:   dw-dates-functions-time.adoc
new file:   dw-dates-functions-today.adoc
new file:   dw-dates-functions-tomorrow.adoc
new file:   dw-dates-functions-yesterday.adoc
new file:   dw-dates-types.adoc
new file:   dw-dates.adoc
modified:   dw-diff-functions-diff.adoc
modified:   dw-diff-types.adoc
modified:   dw-diff.adoc
new file:   dw-math-functions-acos.adoc
new file:   dw-math-functions-asin.adoc
new file:   dw-math-functions-atan.adoc
new file:   dw-math-functions-cos.adoc
new file:   dw-math-functions-log10.adoc
new file:   dw-math-functions-logn.adoc
new file:   dw-math-functions-sin.adoc
new file:   dw-math-functions-tan.adoc
new file:   dw-math-functions-todegrees.adoc
new file:   dw-math-functions-toradians.adoc
new file:   dw-math-variables.adoc
new file:   dw-math.adoc
modified:   dw-mule-functions-causedby.adoc
modified:   dw-mule-functions-lookup.adoc
modified:   dw-mule-functions-p.adoc
modified:   dw-mule-types.adoc
modified:   dw-mule.adoc
modified:   dw-multipart-functions-field.adoc
modified:   dw-multipart-functions-file.adoc
modified:   dw-multipart-functions-form.adoc
modified:   dw-multipart-functions-generateboundary.adoc
modified:   dw-multipart-types.adoc
modified:   dw-multipart.adoc
modified:   dw-numbers-functions-frombinary.adoc
modified:   dw-numbers-functions-fromhex.adoc
modified:   dw-numbers-functions-fromradixnumber.adoc
modified:   dw-numbers-functions-tobinary.adoc
modified:   dw-numbers-functions-tohex.adoc
modified:   dw-numbers-functions-toradixnumber.adoc
modified:   dw-numbers.adoc
modified:   dw-objects-functions-divideby.adoc
modified:   dw-objects-functions-entryset.adoc
modified:   dw-objects-functions-everyentry.adoc
modified:   dw-objects-functions-keyset.adoc
modified:   dw-objects-functions-mergewith.adoc
modified:   dw-objects-functions-nameset.adoc
modified:   dw-objects-functions-someentry.adoc
modified:   dw-objects-functions-takewhile.adoc
modified:   dw-objects-functions-valueset.adoc
modified:   dw-objects.adoc
new file:   dw-periods-functions-between.adoc
new file:   dw-periods-functions-days.adoc
new file:   dw-periods-functions-duration.adoc
new file:   dw-periods-functions-hours.adoc
new file:   dw-periods-functions-minutes.adoc
new file:   dw-periods-functions-months.adoc
new file:   dw-periods-functions-period.adoc
new file:   dw-periods-functions-seconds.adoc
new file:   dw-periods-functions-years.adoc
new file:   dw-periods.adoc
new file:   dw-runtime-functions-dataformatsdescriptor.adoc
new file:   dw-runtime-functions-eval.adoc
new file:   dw-runtime-functions-evalurl.adoc
modified:   dw-runtime-functions-fail.adoc
modified:   dw-runtime-functions-failif.adoc
modified:   dw-runtime-functions-locationstring.adoc
modified:   dw-runtime-functions-orelse.adoc
modified:   dw-runtime-functions-orelsetry.adoc
modified:   dw-runtime-functions-prop.adoc
modified:   dw-runtime-functions-props.adoc
new file:   dw-runtime-functions-run.adoc
new file:   dw-runtime-functions-runurl.adoc
modified:   dw-runtime-functions-try.adoc
modified:   dw-runtime-functions-wait.adoc
modified:   dw-runtime-types.adoc
modified:   dw-runtime.adoc
modified:   dw-strings-functions-appendifmissing.adoc
modified:   dw-strings-functions-camelize.adoc
modified:   dw-strings-functions-capitalize.adoc
modified:   dw-strings-functions-charcode.adoc
modified:   dw-strings-functions-charcodeat.adoc
new file:   dw-strings-functions-collapse.adoc
new file:   dw-strings-functions-countcharactersby.adoc
new file:   dw-strings-functions-countmatches.adoc
modified:   dw-strings-functions-dasherize.adoc
new file:   dw-strings-functions-everycharacter.adoc
new file:   dw-strings-functions-first.adoc
modified:   dw-strings-functions-fromcharcode.adoc
new file:   dw-strings-functions-hammingdistance.adoc
modified:   dw-strings-functions-isalpha.adoc
modified:   dw-strings-functions-isalphanumeric.adoc
modified:   dw-strings-functions-islowercase.adoc
modified:   dw-strings-functions-isnumeric.adoc
modified:   dw-strings-functions-isuppercase.adoc
modified:   dw-strings-functions-iswhitespace.adoc
new file:   dw-strings-functions-last.adoc
modified:   dw-strings-functions-leftpad.adoc
new file:   dw-strings-functions-levenshteindistance.adoc
new file:   dw-strings-functions-lines.adoc
new file:   dw-strings-functions-mapstring.adoc
modified:   dw-strings-functions-ordinalize.adoc
modified:   dw-strings-functions-pluralize.adoc
modified:   dw-strings-functions-prependifmissing.adoc
new file:   dw-strings-functions-remove.adoc
modified:   dw-strings-functions-repeat.adoc
new file:   dw-strings-functions-replaceall.adoc
new file:   dw-strings-functions-reverse.adoc
modified:   dw-strings-functions-rightpad.adoc
modified:   dw-strings-functions-singularize.adoc
new file:   dw-strings-functions-somecharacter.adoc
new file:   dw-strings-functions-substring.adoc
modified:   dw-strings-functions-substringafter.adoc
modified:   dw-strings-functions-substringafterlast.adoc
modified:   dw-strings-functions-substringbefore.adoc
modified:   dw-strings-functions-substringbeforelast.adoc
new file:   dw-strings-functions-substringby.adoc
new file:   dw-strings-functions-substringevery.adoc
modified:   dw-strings-functions-underscore.adoc
modified:   dw-strings-functions-unwrap.adoc
modified:   dw-strings-functions-withmaxsize.adoc
new file:   dw-strings-functions-words.adoc
modified:   dw-strings-functions-wrapifmissing.adoc
modified:   dw-strings-functions-wrapwith.adoc
modified:   dw-strings.adoc
modified:   dw-system-functions-envvar.adoc
modified:   dw-system-functions-envvars.adoc
modified:   dw-system.adoc
modified:   dw-timer-functions-currentmilliseconds.adoc
modified:   dw-timer-functions-duration.adoc
modified:   dw-timer-functions-time.adoc
modified:   dw-timer-functions-tomilliseconds.adoc
modified:   dw-timer-types.adoc
modified:   dw-timer.adoc
modified:   dw-tree-functions-asexpressionstring.adoc
new file:   dw-tree-functions-filterarrayleafs.adoc
new file:   dw-tree-functions-filterobjectleafs.adoc
new file:   dw-tree-functions-filtertree.adoc
new file:   dw-tree-functions-isarraytype.adoc
new file:   dw-tree-functions-isattributetype.adoc
new file:   dw-tree-functions-isobjecttype.adoc
modified:   dw-tree-functions-mapleafvalues.adoc
modified:   dw-tree-functions-nodeexists.adoc
modified:   dw-tree-types.adoc
modified:   dw-tree-variables.adoc
modified:   dw-tree.adoc
modified:   dw-types-functions-arrayitem.adoc
modified:   dw-types-functions-basetypeof.adoc
modified:   dw-types-functions-functionparamtypes.adoc
modified:   dw-types-functions-functionreturntype.adoc
modified:   dw-types-functions-intersectionitems.adoc
modified:   dw-types-functions-isanytype.adoc
modified:   dw-types-functions-isarraytype.adoc
modified:   dw-types-functions-isbinarytype.adoc
modified:   dw-types-functions-isbooleantype.adoc
modified:   dw-types-functions-isdatetimetype.adoc
modified:   dw-types-functions-isdatetype.adoc
modified:   dw-types-functions-isfunctiontype.adoc
modified:   dw-types-functions-isintersectiontype.adoc
modified:   dw-types-functions-iskeytype.adoc
modified:   dw-types-functions-isliteraltype.adoc
modified:   dw-types-functions-islocaldatetimetype.adoc
modified:   dw-types-functions-islocaltimetype.adoc
modified:   dw-types-functions-isnamespacetype.adoc
modified:   dw-types-functions-isnothingtype.adoc
modified:   dw-types-functions-isnulltype.adoc
modified:   dw-types-functions-isnumbertype.adoc
modified:   dw-types-functions-isobjecttype.adoc
modified:   dw-types-functions-isperiodtype.adoc
modified:   dw-types-functions-israngetype.adoc
modified:   dw-types-functions-isreferencetype.adoc
modified:   dw-types-functions-isregextype.adoc
modified:   dw-types-functions-isstringtype.adoc
modified:   dw-types-functions-istimetype.adoc
modified:   dw-types-functions-istimezonetype.adoc
modified:   dw-types-functions-istypetype.adoc
modified:   dw-types-functions-isuniontype.adoc
modified:   dw-types-functions-isuritype.adoc
modified:   dw-types-functions-literalvalueof.adoc
modified:   dw-types-functions-metadataof.adoc
modified:   dw-types-functions-nameof.adoc
modified:   dw-types-functions-objectfields.adoc
modified:   dw-types-functions-unionitems.adoc
modified:   dw-types-types.adoc
modified:   dw-types.adoc
modified:   dw-url-functions-compose.adoc
modified:   dw-url-functions-decodeuri.adoc
modified:   dw-url-functions-decodeuricomponent.adoc
modified:   dw-url-functions-encodeuri.adoc
modified:   dw-url-functions-encodeuricomponent.adoc
modified:   dw-url-functions-parseuri.adoc
modified:   dw-url-types.adoc
modified:   dw-url.adoc
modified:   dw-values-functions-attr.adoc
modified:   dw-values-functions-field.adoc
modified:   dw-values-functions-index.adoc
modified:   dw-values-functions-mask.adoc
modified:   dw-values-functions-update.adoc
new file:   dw-values-types.adoc
modified:   dw-values.adoc
////
